import type { Article, GovernmentResponse, FilterOptions, Region, MediaType } from './types';
import { PlaceHolderImages } from './placeholder-images';

const getImage = (id: string) => {
    const img = PlaceHolderImages.find(p => p.id === id);
    if (!img) return { imageUrl: "https://picsum.photos/seed/error/600/400", imageHint: "placeholder image" };
    return { imageUrl: img.imageUrl, imageHint: img.imageHint };
}

export const articles: Article[] = [
  {
    id: 'article-1',
    title_en: 'Mount Sinabung Erupts, Spews Ash Column 3,000 Meters High',
    title_id: 'Gunung Sinabung Meletus, Semburkan Kolom Abu Setinggi 3.000 Meter',
    source: 'National News Agency',
    date: '2024-11-05T08:00:00Z',
    content_en: 'Mount Sinabung in North Sumatra erupted again, spewing a thick column of volcanic ash up to 3,000 meters into the sky. Local residents are advised to stay away from the red zone.',
    content_id: 'Gunung Sinabung di Sumatra Utara kembali meletus, menyemburkan kolom abu vulkanik tebal hingga 3.000 meter ke langit. Warga setempat diimbau untuk menjauhi zona merah.',
    ...getImage('volcano-eruption-1'),
    videoUrl: 'https://storage.googleapis.com/gtv-videos-bucket/sample/ForBiggerFun.mp4',
    region: 'North Sumatra',
    mediaType: 'Online News',
    sentiment: 'Negative',
    sentimentReason_en: 'The article reports on a dangerous natural disaster, which is a negative event posing a threat to local communities.',
    sentimentReason_id: 'Artikel ini melaporkan bencana alam berbahaya, yang merupakan peristiwa negatif yang menjadi ancaman bagi masyarakat setempat.',
  },
  {
    id: 'article-2',
    title_en: 'Landslide in West Java Buries Several Homes',
    title_id: 'Tanah Longsor di Jawa Barat Timbun Beberapa Rumah',
    source: 'Regional Gazette',
    date: '2024-11-04T18:30:00Z',
    content_en: 'Heavy rainfall triggered a landslide in a hilly area of West Java, burying at least five homes. Search and rescue teams are currently at the location to find potential victims.',
    content_id: 'Hujan deras memicu tanah longsor di daerah perbukitan di Jawa Barat, menimbun sedikitnya lima rumah. Tim pencari dan penyelamat saat ini berada di lokasi untuk mencari korban yang mungkin tertimbun.',
    ...getImage('landslide-search-2'),
    videoUrl: 'https://storage.googleapis.com/gtv-videos-bucket/sample/ForBiggerJoy.mp4',
    region: 'West Sumatra',
    mediaType: 'Online News',
    sentiment: 'Negative',
    sentimentReason_en: 'Reports on a tragic event involving loss of property and potential loss of life, indicating a severe negative situation.',
    sentimentReason_id: 'Melaporkan peristiwa tragis yang melibatkan kehilangan harta benda dan potensi korban jiwa, yang menunjukkan situasi negatif yang parah.',
  },
  {
    id: 'article-3',
    title_en: 'Community Kitchens Established for Aceh Flood Evacuees',
    title_id: 'Dapur Umum Didirikan untuk Pengungsi Banjir Aceh',
    source: 'Community Voice Portal',
    date: '2024-11-06T11:00:00Z',
    content_en: 'Local NGOs and volunteers have established community kitchens in several evacuation centers in Aceh, providing thousands of warm meals for families displaced by the recent floods.',
    content_id: 'LSM lokal dan sukarelawan telah mendirikan dapur umum di beberapa pusat evakuasi di Aceh, menyediakan ribuan makanan hangat untuk keluarga yang mengungsi akibat banjir baru-baru ini.',
    ...getImage('community-kitchen-3'),
    videoUrl: 'https://storage.googleapis.com/gtv-videos-bucket/sample/ForBiggerMeltdowns.mp4',
    region: 'Aceh',
    mediaType: 'Social Media',
    sentiment: 'Positive',
    sentimentReason_en: 'Highlights a positive and proactive community effort to help those in need during a disaster.',
    sentimentReason_id: 'Menyoroti upaya komunitas yang positif dan proaktif untuk membantu mereka yang membutuhkan selama bencana.',
  },
  {
    id: 'article-4',
    title_en: 'Government Accelerates Infrastructure Repair Post-Flood',
    title_id: 'Pemerintah Percepat Perbaikan Infrastruktur Pascabanjir',
    source: 'Presidential Office',
    date: '2024-11-07T15:00:00Z',
    content_en: 'The Ministry of Public Works has been instructed to accelerate the repair of roads and bridges damaged by floods in North Sumatra to restore connectivity and economic activity.',
    content_id: 'Kementerian Pekerjaan Umum telah diinstruksikan untuk mempercepat perbaikan jalan dan jembatan yang rusak akibat banjir di Sumatra Utara untuk memulihkan konektivitas dan kegiatan ekonomi.',
    ...getImage('infrastructure-repair-4'),
    videoUrl: 'https://storage.googleapis.com/gtv-videos-bucket/sample/Sintel.mp4',
    region: 'North Sumatra',
    mediaType: 'Press Release',
    sentiment: 'Positive',
    sentimentReason_en: 'The government is taking concrete steps to repair damage and restore normalcy, which is a positive action.',
    sentimentReason_id: 'Pemerintah mengambil langkah nyata untuk memperbaiki kerusakan dan memulihkan keadaan normal, yang merupakan tindakan positif.',
  },
  {
    id: 'article-5',
    title_en: 'Online Petition for Better Disaster Warning System Goes Viral',
    title_id: 'Petisi Online untuk Sistem Peringatan Bencana yang Lebih Baik Menjadi Viral',
    source: 'Social Media Aggregator',
    date: '2024-11-06T20:00:00Z',
    content_en: 'A citizen-led online petition urging the government to improve its early warning systems for natural disasters has garnered over 100,000 signatures in just two days.',
    content_id: 'Sebuah petisi online yang dipimpin oleh warga mendesak pemerintah untuk meningkatkan sistem peringatan dini bencana alam telah mengumpulkan lebih dari 100.000 tanda tangan hanya dalam dua hari.',
    ...getImage('online-petition-5'),
    videoUrl: 'https://storage.googleapis.com/gtv-videos-bucket/sample/SubaruOutbackOnStreetAndDirt.mp4',
    region: 'Aceh',
    mediaType: 'Social Media',
    sentiment: 'Neutral',
    sentimentReason_en: 'Reports on a civic action (a petition) without taking a stance on its content. It reflects public concern, which is neutral from a reporting standpoint.',
    sentimentReason_id: 'Melaporkan tindakan sipil (petisi) tanpa mengambil sikap terhadap isinya. Ini mencerminkan keprihatinan publik, yang netral dari sudut pandang peliputan.',
  },
  {
    id: 'article-6',
    title_en: 'International Aid Arrives for West Sumatra Flood Victims',
    title_id: 'Bantuan Internasional Tiba untuk Korban Banjir Sumatra Barat',
    source: 'International Reporter',
    date: '2024-11-08T09:00:00Z',
    content_en: 'The first shipment of international aid, including tents, blankets, and medical supplies, has arrived at the main airport in West Sumatra to be distributed to flood-affected areas.',
    content_id: 'Pengiriman pertama bantuan internasional, termasuk tenda, selimut, dan pasokan medis, telah tiba di bandara utama di Sumatra Barat untuk didistribusikan ke daerah yang terkena dampak banjir.',
    ...getImage('aid-plane-6'),
    videoUrl: 'https://storage.googleapis.com/gtv-videos-bucket/sample/TearsOfSteel.mp4',
    region: 'West Sumatra',
    mediaType: 'Online News',
    sentiment: 'Positive',
    sentimentReason_en: 'The arrival of international aid is a positive development that will help alleviate the suffering of disaster victims.',
    sentimentReason_id: 'Kedatangan bantuan internasional adalah perkembangan positif yang akan membantu meringankan penderitaan para korban bencana.',
  },
];

export const governmentResponses: GovernmentResponse[] = [
  {
    id: 'response-1',
    title_en: 'BNPB Dispatches Emergency Response Teams',
    title_id: 'BNPB Mengirim Tim Tanggap Darurat',
    source: 'BNPB (National Disaster Management Agency)',
    date: '2024-10-26T12:00:00Z',
    content_en: 'The National Disaster Management Agency (BNPB) has dispatched three emergency response teams to Aceh to assist with evacuation and initial damage assessment.',
    content_id: 'Badan Nasional Penanggulangan Bencana (BNPB) telah mengirimkan tiga tim tanggap darurat ke Aceh untuk membantu evakuasi dan penilaian kerusakan awal.',
  },
  {
    id: 'response-2',
    title_en: 'Ministry of Social Affairs Sets Up Public Kitchens',
    title_id: 'Kementerian Sosial Mendirikan Dapur Umum',
    source: 'Ministry of Social Affairs',
    date: '2024-10-28T11:00:00Z',
    content_en: 'The Ministry of Social Affairs has established several public kitchens in West Sumatra to provide hot meals for evacuees. The kitchens are expected to serve thousands of people daily.',
    content_id: 'Kementerian Sosial telah mendirikan beberapa dapur umum di Sumatra Barat untuk menyediakan makanan hangat bagi para pengungsi. Dapur umum tersebut diharapkan dapat melayani ribuan orang setiap hari.',
  },
  {
    id: 'response-3',
    title_en: 'Infrastructure Repair to Begin Immediately',
    title_id: 'Perbaikan Infrastruktur Akan Dimulai Segera',
    source: 'Ministry of Public Works',
    date: '2024-10-29T15:00:00Z',
    content_en: 'The Ministry of Public Works and Public Housing has announced that emergency repairs on critical infrastructure, including bridges and roads in North Sumatra, will commence as soon as conditions permit.',
    content_id: 'Kementerian Pekerjaan Umum dan Perumahan Rakyat telah mengumumkan bahwa perbaikan darurat pada infrastruktur penting, termasuk jembatan dan jalan di Sumatra Utara, akan dimulai segera setelah kondisi memungkinkan.',
  },
];

export const filterOptions: FilterOptions = {
  regions: ['Aceh', 'North Sumatra', 'West Sumatra'],
  mediaTypes: ['Online News', 'Social Media', 'Press Release'],
  sources: [
    'National News Agency',
    'Regional Gazette',
    'Community Voice Portal',
    'Presidential Office',
    'Social Media Aggregator',
    'International Reporter',
  ],
};
