import type { Article, GovernmentResponse, FilterOptions, Region, MediaType } from './types';
import { PlaceHolderImages } from './placeholder-images';

const getImage = (id: string) => {
    const img = PlaceHolderImages.find(p => p.id === id);
    if (!img) return { imageUrl: "https://picsum.photos/seed/error/600/400", imageHint: "placeholder image" };
    return { imageUrl: img.imageUrl, imageHint: img.imageHint };
}

export const articles: Article[] = [
  {
    id: 'article-1',
    title_en: 'Flash Floods Inundate Hundreds of Homes in Aceh',
    title_id: 'Banjir Bandang Rendam Ratusan Rumah di Aceh',
    source: 'National News Agency',
    date: '2024-10-26T10:00:00Z',
    content_en: 'Hundreds of homes in several districts of Aceh have been submerged by flash floods following hours of heavy rainfall. Rescue teams have been deployed to evacuate residents trapped in their homes.',
    content_id: 'Ratusan rumah di beberapa kabupaten di Aceh terendam banjir bandang setelah hujan deras selama berjam-jam. Tim penyelamat telah dikerahkan untuk mengevakuasi warga yang terjebak di rumah mereka.',
    ...getImage('flood-aerial-1'),
    videoUrl: 'https://storage.googleapis.com/gtv-videos-bucket/sample/ForBiggerFun.mp4',
    region: 'Aceh',
    mediaType: 'Online News',
    sentiment: 'Negative',
    sentimentReason_en: 'The article reports on a natural disaster causing significant property damage and requiring emergency evacuations, which are negative events.',
    sentimentReason_id: 'Artikel ini melaporkan bencana alam yang menyebabkan kerusakan properti yang signifikan dan memerlukan evakuasi darurat, yang merupakan peristiwa negatif.',
  },
  {
    id: 'article-2',
    title_en: 'North Sumatra Declares State of Emergency Amidst Worsening Floods',
    title_id: 'Sumatra Utara Umumkan Keadaan Darurat di Tengah Banjir yang Memburuk',
    source: 'Regional Gazette',
    date: '2024-10-27T14:30:00Z',
    content_en: 'The North Sumatra provincial government has officially declared a state of emergency as floodwaters continue to rise, displacing thousands of families and disrupting major transportation routes.',
    content_id: 'Pemerintah provinsi Sumatra Utara secara resmi mengumumkan keadaan darurat karena air banjir terus naik, membuat ribuan keluarga mengungsi dan mengganggu jalur transportasi utama.',
    ...getImage('damaged-homes-6'),
    videoUrl: 'https://storage.googleapis.com/gtv-videos-bucket/sample/ForBiggerJoy.mp4',
    region: 'North Sumatra',
    mediaType: 'Online News',
    sentiment: 'Negative',
    sentimentReason_en: 'Describes a worsening crisis, displacement of people, and disruption of infrastructure, indicating a severe negative situation.',
    sentimentReason_id: 'Menggambarkan krisis yang memburuk, pengungsian orang, dan gangguan infrastruktur, yang menunjukkan situasi negatif yang parah.',
  },
  {
    id: 'article-3',
    title_en: 'Volunteers Mobilize to Provide Aid in West Sumatra',
    title_id: 'Sukarelawan Bergerak Memberikan Bantuan di Sumatra Barat',
    source: 'Community Voice Portal',
    date: '2024-10-28T09:00:00Z',
    content_en: 'Following the devastating floods, communities across West Sumatra have come together. Volunteers are mobilizing to distribute food, water, and medical supplies to affected areas, showcasing incredible community spirit.',
    content_id: 'Setelah banjir yang menghancurkan, komunitas di seluruh Sumatra Barat telah bersatu. Sukarelawan bergerak untuk mendistribusikan makanan, air, dan pasokan medis ke daerah-daerah yang terkena dampak, menunjukkan semangat komunitas yang luar biasa.',
    ...getImage('aid-distribution-3'),
    videoUrl: 'https://storage.googleapis.com/gtv-videos-bucket/sample/ForBiggerMeltdowns.mp4',
    region: 'West Sumatra',
    mediaType: 'Social Media',
    sentiment: 'Positive',
    sentimentReason_en: 'Focuses on the positive community response, solidarity, and volunteer efforts to help victims, which is an uplifting aspect of the situation.',
    sentimentReason_id: 'Berfokus pada respons komunitas yang positif, solidaritas, dan upaya sukarelawan untuk membantu korban, yang merupakan aspek yang membangkitkan semangat dari situasi tersebut.',
  },
  {
    id: 'article-4',
    title_en: 'Government Pledges Swift Action and Aid for Flood Victims',
    title_id: 'Pemerintah Janjikan Tindakan Cepat dan Bantuan untuk Korban Banjir',
    source: 'Presidential Office',
    date: '2024-10-28T16:00:00Z',
    content_en: 'In a press conference today, the central government pledged to take swift action to address the flood crisis. An initial aid package has been approved for immediate distribution to Aceh, North, and West Sumatra.',
    content_id: 'Dalam konferensi pers hari ini, pemerintah pusat berjanji untuk mengambil tindakan cepat untuk mengatasi krisis banjir. Paket bantuan awal telah disetujui untuk didistribusikan segera ke Aceh, Sumatra Utara, dan Sumatra Barat.',
    ...getImage('government-press-conference-4'),
    videoUrl: 'https://storage.googleapis.com/gtv-videos-bucket/sample/Sintel.mp4',
    region: 'Aceh',
    mediaType: 'Press Release',
    sentiment: 'Positive',
    sentimentReason_en: 'The government is making a commitment to provide aid and take action, which is a positive step towards resolving the crisis.',
    sentimentReason_id: 'Pemerintah membuat komitmen untuk memberikan bantuan dan mengambil tindakan, yang merupakan langkah positif menuju penyelesaian krisis.',
  },
  {
    id: 'article-5',
    title_en: 'Citizens take to social media to share flood updates #AcehFlood',
    title_id: 'Warga menggunakan media sosial untuk berbagi pembaruan banjir #BanjirAceh',
    source: 'Social Media Aggregator',
    date: '2024-10-27T18:00:00Z',
    content_en: 'Thousands of posts with the hashtag #AcehFlood are circulating on social media, showing real-time images and videos of the situation on the ground. Many are calling for more urgent government intervention.',
    content_id: 'Ribuan postingan dengan tagar #BanjirAceh beredar di media sosial, menunjukkan gambar dan video real-time dari situasi di lapangan. Banyak yang menyerukan intervensi pemerintah yang lebih mendesak.',
    ...getImage('social-media-feed-5'),
    videoUrl: 'https://storage.googleapis.com/gtv-videos-bucket/sample/SubaruOutbackOnStreetAndDirt.mp4',
    region: 'Aceh',
    mediaType: 'Social Media',
    sentiment: 'Neutral',
    sentimentReason_en: 'The article reports on the use of social media for information dissemination. While the content shared may be negative, the act of sharing itself is reported neutrally. It also contains a mix of reporting and calls for action.',
    sentimentReason_id: 'Artikel ini melaporkan penggunaan media sosial untuk penyebaran informasi. Meskipun konten yang dibagikan mungkin negatif, tindakan berbagi itu sendiri dilaporkan secara netral. Ini juga berisi campuran pelaporan dan seruan untuk bertindak.',
  },
  {
    id: 'article-6',
    title_en: 'Rescue Efforts Hampered by Difficult Terrain in North Sumatra',
    title_id: 'Upaya Penyelamatan Terhambat oleh Medan Sulit di Sumatra Utara',
    source: 'International Reporter',
    date: '2024-10-29T11:00:00Z',
    content_en: 'Rescue operations in the remote areas of North Sumatra are facing significant challenges due to landslides and damaged roads. Aid workers are struggling to reach some of the worst-hit villages.',
    content_id: 'Operasi penyelamatan di daerah terpencil Sumatra Utara menghadapi tantangan signifikan karena tanah longsor dan jalan yang rusak. Pekerja bantuan berjuang untuk mencapai beberapa desa yang paling parah terkena dampak.',
    ...getImage('rescue-operation-2'),
    videoUrl: 'https://storage.googleapis.com/gtv-videos-bucket/sample/TearsOfSteel.mp4',
    region: 'North Sumatra',
    mediaType: 'Online News',
    sentiment: 'Negative',
    sentimentReason_en: 'Highlights obstacles and difficulties in the rescue operations, which is a negative development in the disaster response.',
    sentimentReason_id: 'Menyoroti hambatan dan kesulitan dalam operasi penyelamatan, yang merupakan perkembangan negatif dalam respons bencana.',
  },
];

export const governmentResponses: GovernmentResponse[] = [
  {
    id: 'response-1',
    title_en: 'BNPB Dispatches Emergency Response Teams',
    title_id: 'BNPB Mengirim Tim Tanggap Darurat',
    source: 'BNPB (National Disaster Management Agency)',
    date: '2024-10-26T12:00:00Z',
    content_en: 'The National Disaster Management Agency (BNPB) has dispatched three emergency response teams to Aceh to assist with evacuation and initial damage assessment.',
    content_id: 'Badan Nasional Penanggulangan Bencana (BNPB) telah mengirimkan tiga tim tanggap darurat ke Aceh untuk membantu evakuasi dan penilaian kerusakan awal.',
  },
  {
    id: 'response-2',
    title_en: 'Ministry of Social Affairs Sets Up Public Kitchens',
    title_id: 'Kementerian Sosial Mendirikan Dapur Umum',
    source: 'Ministry of Social Affairs',
    date: '2024-10-28T11:00:00Z',
    content_en: 'The Ministry of Social Affairs has established several public kitchens in West Sumatra to provide hot meals for evacuees. The kitchens are expected to serve thousands of people daily.',
    content_id: 'Kementerian Sosial telah mendirikan beberapa dapur umum di Sumatra Barat untuk menyediakan makanan hangat bagi para pengungsi. Dapur umum tersebut diharapkan dapat melayani ribuan orang setiap hari.',
  },
  {
    id: 'response-3',
    title_en: 'Infrastructure Repair to Begin Immediately',
    title_id: 'Perbaikan Infrastruktur Akan Dimulai Segera',
    source: 'Ministry of Public Works',
    date: '2024-10-29T15:00:00Z',
    content_en: 'The Ministry of Public Works and Public Housing has announced that emergency repairs on critical infrastructure, including bridges and roads in North Sumatra, will commence as soon as conditions permit.',
    content_id: 'Kementerian Pekerjaan Umum dan Perumahan Rakyat telah mengumumkan bahwa perbaikan darurat pada infrastruktur penting, termasuk jembatan dan jalan di Sumatra Utara, akan dimulai segera setelah kondisi memungkinkan.',
  },
];

export const filterOptions: FilterOptions = {
  regions: ['Aceh', 'North Sumatra', 'West Sumatra'],
  mediaTypes: ['Online News', 'Social Media', 'Press Release'],
  sources: [
    'National News Agency',
    'Regional Gazette',
    'Community Voice Portal',
    'Presidential Office',
    'Social Media Aggregator',
    'International Reporter',
  ],
};
