import type { Article, GovernmentResponse, FilterOptions, Region, MediaType } from './types';
import { PlaceHolderImages } from './placeholder-images';

const getImage = (id: string) => {
    const img = PlaceHolderImages.find(p => p.id === id);
    if (!img) return { imageUrl: "https://picsum.photos/seed/error/600/400", imageHint: "placeholder image" };
    return { imageUrl: img.imageUrl, imageHint: img.imageHint };
}

export const articles: Article[] = [
  {
    id: 'article-1',
    title_en: 'West Aceh Devastated by Flash Floods, Thousands Displaced',
    title_id: 'Aceh Barat Diterjang Banjir Bandang, Ribuan Warga Mengungsi',
    source: 'National News Agency',
    date: '2025-11-28T09:00:00Z',
    content_en: 'A devastating flash flood, carrying logs and mud, swept through residential areas in West Aceh at the end of November 2025. Thousands of homes were destroyed, and the death toll is expected to rise as search and rescue teams navigate the difficult terrain. This is the worst environmental crisis of the year.',
    content_id: 'Banjir bandang dahsyat yang membawa material kayu dan lumpur menyapu pemukiman warga di Aceh Barat pada akhir November 2025. Ribuan rumah hancur, dan jumlah korban jiwa diperkirakan akan terus bertambah seiring tim SAR mengevakuasi medan yang sulit. Ini adalah krisis lingkungan terparah tahun ini.',
    ...getImage('flood-destruction-1'),
    videoUrl: 'https://storage.googleapis.com/gtv-videos-bucket/sample/ForBiggerFun.mp4',
    region: 'Aceh',
    mediaType: 'Online News',
    sentiment: 'Negative',
    sentimentReason_en: 'Reports on a massive natural disaster, focusing on destruction, displacement, and loss of life.',
    sentimentReason_id: 'Melaporkan bencana alam masif, dengan fokus pada kehancuran, pengungsian, dan korban jiwa.',
  },
  {
    id: 'article-2',
    title_en: 'Deforestation in Bukit Barisan Blamed for Deadly North Sumatra Landslides',
    title_id: 'Deforestasi di Bukit Barisan Dituding Jadi Penyebab Longsor Mematikan di Sumatera Utara',
    source: 'Investigative Weekly',
    date: '2025-11-29T14:00:00Z',
    content_en: 'Environmental experts point to rampant deforestation and land conversion in protected forest areas as the main cause of the massive destruction. Weak supervision of land-use permits has led to the watershed losing its capacity to absorb rainfall, turning extreme weather into a deadly runoff.',
    content_id: 'Pakar lingkungan menunjuk deforestasi dan alih fungsi lahan di kawasan hutan lindung sebagai penyebab utama kehancuran masif. Lemahnya pengawasan izin pembukaan lahan mengakibatkan daerah aliran sungai (DAS) kehilangan daya dukung, mengubah cuaca ekstrem menjadi aliran permukaan yang mematikan.',
    ...getImage('deforestation-impact-2'),
    videoUrl: 'https://storage.googleapis.com/gtv-videos-bucket/sample/ForBiggerJoy.mp4',
    region: 'North Sumatra',
    mediaType: 'Online News',
    sentiment: 'Negative',
    sentimentReason_en: 'Critically analyzes the root cause of the disaster, linking it to policy and enforcement failures.',
    sentimentReason_id: 'Menganalisis secara kritis akar penyebab bencana, menghubungkannya dengan kegagalan kebijakan dan penegakan hukum.',
  },
  {
    id: 'article-3',
    title_en: 'Panic on Social Media Hampers Evacuation Efforts in West Sumatra',
    title_id: 'Kepanikan di Media Sosial Hambat Upaya Evakuasi di Sumatera Barat',
    source: 'Digital Trends',
    date: '2025-11-28T22:00:00Z',
    content_en: 'During the initial hours of the crisis, social media was flooded with panic-driven narratives and misinformation rather than systematic evacuation instructions. This information gap between authorities and grassroots communities potentially increased the number of victims due to confusion.',
    content_id: 'Pada jam-jam awal krisis, media sosial dibanjiri narasi kepanikan dan disinformasi dibandingkan instruksi evakuasi yang sistematis. Kesenjangan informasi antara otoritas dan masyarakat akar rumput ini berpotensi meningkatkan jumlah korban akibat kebingungan.',
    ...getImage('social-media-panic-3'),
    videoUrl: 'https://storage.googleapis.com/gtv-videos-bucket/sample/ForBiggerMeltdowns.mp4',
    region: 'West Sumatra',
    mediaType: 'Social Media',
    sentiment: 'Neutral',
    sentimentReason_en: 'Reports on the role of social media and information flow during the crisis without taking a definitive positive or negative stance.',
    sentimentReason_id: 'Melaporkan peran media sosial dan arus informasi selama krisis tanpa mengambil sikap positif atau negatif yang definitif.',
  },
  {
    id: 'article-4',
    title_en: 'Government Deploys Emergency Aid, Promises Structural Ecological Reforms',
    title_id: 'Pemerintah Kerahkan Bantuan Darurat, Janjikan Reformasi Ekologis Struktural',
    source: 'Presidential Office',
    date: '2025-12-01T16:00:00Z',
    content_en: 'In response to the devastating flash floods, the government has dispatched emergency aid to all three provinces. The President also stated that this disaster highlights the failure of environmental management and promised a thorough review of spatial planning policies and a crackdown on illegal logging.',
    content_id: 'Menanggapi banjir bandang yang menghancurkan, pemerintah telah mengirimkan bantuan darurat ke tiga provinsi. Presiden juga menyatakan bahwa bencana ini menyoroti kegagalan pengelolaan lingkungan dan menjanjikan peninjauan menyeluruh terhadap kebijakan tata ruang serta penindakan tegas terhadap pembalakan liar.',
    ...getImage('government-press-conference-4'),
    videoUrl: 'https://storage.googleapis.com/gtv-videos-bucket/sample/Sintel.mp4',
    region: 'Aceh',
    mediaType: 'Press Release',
    sentiment: 'Positive',
    sentimentReason_en: 'Reports on the government\'s positive response, including providing aid and committing to long-term structural changes.',
    sentimentReason_id: 'Melaporkan respons positif pemerintah, termasuk penyediaan bantuan dan komitmen terhadap perubahan struktural jangka panjang.',
  },
  {
    id: 'article-5',
    title_en: 'Media Framing Under Scrutiny: Sensationalism Over Critical Analysis',
    title_id: 'Framing Media Disorot: Sensasionalisme Kalahkan Analisis Kritis',
    source: 'Media Watchdog',
    date: '2025-12-02T11:00:00Z',
    content_en: 'An analysis of media coverage reveals that many outlets focused on sensational framing, highlighting the natural aspects of the disaster without deeply criticizing the misguided spatial planning policies. This ambiguous role of the media is now a subject of public debate.',
    content_id: 'Analisis liputan media menunjukkan bahwa banyak outlet berfokus pada pembingkaian sensasional, menonjolkan aspek alam dari bencana tanpa mengkritik secara mendalam kebijakan tata ruang yang salah arah. Peran ambigu media ini kini menjadi subjek perdebatan publik.',
    ...getImage('media-analysis-5'),
    videoUrl: 'https://storage.googleapis.com/gtv-videos-bucket/sample/SubaruOutbackOnStreetAndDirt.mp4',
    region: 'North Sumatra',
    mediaType: 'Online News',
    sentiment: 'Neutral',
    sentimentReason_en: 'Objectively discusses the media\'s role and framing strategies, which is a neutral analytical perspective.',
    sentimentReason_id: 'Membahas secara objektif peran media dan strategi pembingkaian, yang merupakan perspektif analisis netral.',
  },
  {
    id: 'article-6',
    title_en: 'Volunteers and NGOs Mobilize to Establish Public Kitchens for Evacuees',
    title_id: 'Sukarelawan dan LSM Bergerak Mendirikan Dapur Umum untuk Pengungsi',
    source: 'Community Voice Portal',
    date: '2025-11-29T18:00:00Z',
    content_en: 'Amidst the chaos, local communities and non-governmental organizations in West Sumatra have rapidly mobilized, setting up public kitchens in evacuation centers to provide essential food for tens of thousands of displaced residents.',
    content_id: 'Di tengah kekacauan, komunitas lokal dan organisasi non-pemerintah di Sumatera Barat telah bergerak cepat, mendirikan dapur umum di pusat-pusat pengungsian untuk menyediakan makanan pokok bagi puluhan ribu warga yang terlantar.',
    ...getImage('community-kitchen-3'),
    videoUrl: 'https://storage.googleapis.com/gtv-videos-bucket/sample/TearsOfSteel.mp4',
    region: 'West Sumatra',
    mediaType: 'Social Media',
    sentiment: 'Positive',
    sentimentReason_en: 'Highlights a positive, grassroots effort to provide aid and support to disaster victims.',
    sentimentReason_id: 'Menyoroti upaya positif dari akar rumput untuk memberikan bantuan dan dukungan kepada korban bencana.',
  },
];

export const governmentResponses: GovernmentResponse[] = [
  {
    id: 'response-1',
    title_en: 'BNPB Declares Emergency Status for Three Provinces',
    title_id: 'BNPB Tetapkan Status Darurat untuk Tiga Provinsi',
    source: 'BNPB (National Disaster Management Agency)',
    date: '2025-11-28T12:00:00Z',
    content_en: 'The National Disaster Management Agency (BNPB) has officially declared a state of emergency for Aceh, North Sumatra, and West Sumatra, enabling the full mobilization of national resources for the response.',
    content_id: 'Badan Nasional Penanggulangan Bencana (BNPB) secara resmi menetapkan status darurat untuk Aceh, Sumatera Utara, dan Sumatera Barat, yang memungkinkan mobilisasi penuh sumber daya nasional untuk penanganan.',
  },
  {
    id: 'response-2',
    title_en: 'President Orders Audit of All Land-Use Permits in Bukit Barisan',
    title_id: 'Presiden Perintahkan Audit Seluruh Izin Pemanfaatan Lahan di Bukit Barisan',
    source: 'Presidential Office',
    date: '2025-12-01T17:00:00Z',
    content_en: 'Following the disaster, the President has ordered an immediate and comprehensive audit of all land-use and logging permits issued along the Bukit Barisan mountain range to identify and revoke those that violate regulations.',
    content_id: 'Setelah bencana terjadi, Presiden memerintahkan audit segera dan komprehensif terhadap semua izin pemanfaatan lahan dan penebangan yang dikeluarkan di sepanjang pegunungan Bukit Barisan untuk mengidentifikasi dan mencabut izin yang melanggar peraturan.',
  },
  {
    id: 'response-3',
    title_en: 'Ministry of Communication to Develop Integrated Disaster Information System',
    title_id: 'Kemenkominfo Akan Bangun Sistem Informasi Bencana Terintegrasi',
    source: 'Ministry of Communication and Informatics',
    date: '2025-12-03T10:00:00Z',
    content_en: 'Learning from the information gap, the Ministry of Communication and Informatics will collaborate with BNPB to build a multi-platform, integrated system to ensure early warnings and evacuation instructions reach at-risk communities effectively.',
    content_id: 'Belajar dari kesenjangan informasi, Kementerian Komunikasi dan Informatika akan bekerja sama dengan BNPB untuk membangun sistem terintegrasi multi-platform guna memastikan peringatan dini dan instruksi evakuasi mencapai masyarakat berisiko secara efektif.',
  },
];

export const filterOptions: FilterOptions = {
  regions: ['Aceh', 'North Sumatra', 'West Sumatra'],
  mediaTypes: ['Online News', 'Social Media', 'Press Release'],
  sources: [
    'National News Agency',
    'Investigative Weekly',
    'Digital Trends',
    'Presidential Office',
    'Media Watchdog',
    'Community Voice Portal',
  ],
};
